---
version: '3'
services:
  gcmg:
    container_name: gcmg
    build:
      context: .
      dockerfile: Dockerfile
    image: dceoy/gcmg:latest
    volumes:
      - ${PWD}:/wd
    working_dir: /wd
    entrypoint:
      - gcmg
