---
name: Test
on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        description: Python version to use
        default: 3.x
  workflow_dispatch:
    inputs:
      python-version:
        required: false
        type: string
        description: Python version to use
        default: 3.x
defaults:
  run:
    shell: bash -euo pipefail {0}
    working-directory: .
jobs:
  cli-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version || '3.x' }}
      - name: Install packages
        run: |
          pip install -U --no-cache-dir pip poetry
          poetry install --no-interaction
      - name: Run unit tests using pytest
        run: |
          poetry run gcmg --version
          poetry run gcmg --help
